# Generated by Django 5.0 on 2024-04-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
